heat_template_version: 2014-10-16

description: >
  This is an example showing how you can do firstboot configuration
  of the nodes via cloud-init.  To enable this, replace the default
  mapping of OS::TripleO::NodeUserData in ../overcloud_resource_registry*

parameters:
  ComputeKernelArgs:
    description: >
      Space seprated list of Kernel args to be update to grub.
      The given args will be appended to existing args of GRUB_CMDLINE_LINUX in file /etc/default/grub
      Example: "intel_iommu=on default_hugepagesz=1GB hugepagesz=1G hugepages=1"
    type: string
    default: ""
  HostIsolatedCoreList:
    description: >
      A list or range of physical CPU cores to be tuned as isolated_cores.
      The given args will be appended to the tuned cpu-partitioning profile.
      Ex. HostIsolatedCoreList: '4-12' will tune cores from 4-12
    type: string
    default: ""

resources:
  userdata:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: compute_kernel_args}

  compute_kernel_args:
    type: OS::Heat::SoftwareConfig
    properties:
      config:
        str_replace:
          template: |
            #!/bin/bash
            sed 's/^\(GRUB_CMDLINE_LINUX=".*\)"/\1 $KERNEL_ARGS isolcpus=$TUNED_CORES"/g' -i /etc/default/grub ;
            grub2-mkconfig -o /etc/grub2.cfg
            createrepo /6wind/.
            touch /etc/yum.repos.d/nuage_6wind.repo
            echo "[nuage_6wind]" >> /etc/yum.repos.d/nuage_6wind.repo
            echo "name=nuage_6wind" >> /etc/yum.repos.d/nuage_6wind.repo
            echo "baseurl=file:///6wind/" >> /etc/yum.repos.d/nuage_6wind.repo
            echo "enabled = 1" >> /etc/yum.repos.d/nuage_6wind.repo
            echo "gpgcheck = 0" >> /etc/yum.repos.d/nuage_6wind.repo
            yum install -y selinux-policy-nuage-avrs
            yum install -y python-pyelftools
            yum install -y dkms
            yum remove -y dpdk
            yum install -y 6windgate*
            yum remove -y nuage-openvswitch
            yum install -y nuage-openvswitch*
            yum install -y nuage-metadata-agent*
            yum install -y virtual-accelerator*
            rm -rf /6wind/repodata
            rm -rf /etc/yum.repos.d/nuage_6wind.repo
            reboot
          params:
            $KERNEL_ARGS: {get_param: ComputeKernelArgs}
            $TUNED_CORES: {get_param: HostIsolatedCoreList}


outputs:
  # This means get_resource from the parent template will get the userdata, see:
  # http://docs.openstack.org/developer/heat/template_guide/composition.html#making-your-template-resource-more-transparent
  # Note this is new-for-kilo, an alternative is returning a value then using
  # get_attr in the parent template instead.
  OS::stack_id:
    value: {get_resource: userdata}
